### ISSUE TITLE
Add Install Instructions for MAMP

### ISSUE THREAD

**Issue by ajwad-shaikh** [ajwad-shaikh/BusKaro#15]
Install instructions have been added only for WAMP since I used it to set up the project.

Would be glad if someone could add instructions for MAMP setup since a lot of contributors asked for the same.

**Comment by martink-rsa** [comment]
Writing instructions. Would you like images or not?

**Comment by ajwad-shaikh** [comment]
Maybe no. Please make sure that the instruction set is foolproof and not machine dependent.

**Comment by martink-rsa** [comment]
> Maybe no. Please make sure that the instruction set is foolproof and not machine dependent.

No problem. I'm installing it on both Windows and Linux (Xubuntu) and am double-checking the steps. Unfortunately my OSX machine is down at the moment so I won't be able to verify if the instructions are the same on OSX. I will try and get someone with OSX to check it, but there is a possibility they might not be able to.

**Comment by ajwad-shaikh** [comment]
Thanks @martink-rsa for any and every contribution to this project!

**Comment by martink-rsa** [comment]
More than happy to help!

I erred in stating that I will test it on Linux. There is no Linux version of MAMP.

[EDIT: An alternative is also to include instructions for LAMP?]

**Comment by mcastre** [comment]
Thanks @martink-rsa and @ajwad-shaikh for working on this!
