### ISSUE TITLE
Footer Position is not constant

### ISSUE THREAD

**Issue by ajwad-shaikh** [ajwad-shaikh/BusKaro#4]
**Describe the bug**
The footer on multiple pages does not stick to the bottom of the page. Instead, it keeps itself at the end of the table whose height is variable

**To Reproduce**

1. Login
2. Click on Booked Ticket History
3. Footer on a floating position midway of the page
4. Go back
5. View Bus Schedule
6. Footer at bottom of the page due to increased page size

**Expected behavior**
Footer stays at the bottom of the page no matter the size/content of the page

**Screenshots**

Footer midway on the page
![image](https://user-images.githubusercontent.com/37571185/65998891-e4c96f80-e4b9-11e9-8010-2ee2ebeeb5a6.png)

Footer at the bottom
![image](https://user-images.githubusercontent.com/37571185/65998965-104c5a00-e4ba-11e9-9ca5-617f5f0fec18.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome

**Additional context**
None

**Comment by thallesbrandao** [comment]
dibs

**Comment by goodeath** [comment]
@ajwad-shaikh Can I take it? I would like to help

**Comment by ajwad-shaikh** [comment]
@goodeath, I am assigning the issue to @thallesbrandao for now. You can raise some other issue and feel free to work on it.
Thanks.
