### ISSUE TITLE
Page length is variable for different functionality

### ISSUE THREAD

**Issue by ajwad-shaikh** [ajwad-shaikh/BusKaro#5]
**Describe the bug**
The size of the page for different functions on the website like the Booked Ticket History, Weekly Schedule, etc. depend upon the content on the page

**To Reproduce**

1. Login
2. Click on Booked Ticket History
3. Page Length is very small
4. Go back
5. Click on Book Tickets
6. Page Size increases due to the size of the content

**Expected behavior**
Ideally, for a web-app like BusKaro, page length should remain constant and elements such as the table that has variable length should be placed inside of a scrollable element

**Screenshots**

Small Page Size. Ends immediately after the table starts (and ends)
![image](https://user-images.githubusercontent.com/37571185/65998891-e4c96f80-e4b9-11e9-8010-2ee2ebeeb5a6.png)

Huge page size. Page length increases.
![image](https://user-images.githubusercontent.com/37571185/65998965-104c5a00-e4ba-11e9-9ca5-617f5f0fec18.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome

**Additional context**
As bus services scale, page length depending on the size of the table will lead to problems in UX. A scrollable element is necessary.

**Comment by 20Koen02** [comment]
I’ll take this

**Comment by 20Koen02** [comment]
I can't create a user or login with an existing user. I get the error 


Fatal error: Uncaught Error: Call to a member function fetch_assoc() on boolean in C:\wamp64\www\BusKaro\index.php on line 154

**Comment by ajwad-shaikh** [comment]
Damn, can you file an issue so that someone can take this up too? @20Koen02

**Comment by ajwad-shaikh** [comment]
@20Koen02 Thanks for filling the issue #14
