### ISSUE TITLE
Copyright symbol has been mistakenly placed in footer

### ISSUE THREAD

**Issue by ajwad-shaikh** [ajwad-shaikh/BusKaro#6]
**Describe the bug**
A copyright symbol has been mistakenly put in the footer despite the open-source nature of the project

**To Reproduce**

1. Go to Dashboard/any other page
3. Scroll down to the footer

**Expected behavior**
There should ideally be a [copyleft symbol](https://en.wikipedia.org/wiki/Copyleft) instead of the copyright

**Screenshots**

Copyright Symbol in the footer

![image](https://user-images.githubusercontent.com/37571185/65998891-e4c96f80-e4b9-11e9-8010-2ee2ebeeb5a6.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome

**Additional context**
None

**Comment by ajwad-shaikh** [comment]
The footer statement is entirely wrong. **All rights reserved** should never be there. Request removal and addition of some open-source friendly footer

**Comment by LordBrud** [comment]
I'll take this

**Comment by ajwad-shaikh** [comment]
Assigning the issue to @LordBrud because he commented first.

**Comment by ajwad-shaikh** [comment]
Fixed with #9
